excerpt_separator: ""
pygments: true
markdown: kramdown
url: https://jrolstad.github.io
title: Rolstad Recipes
tagline: Rolstad Family Recipes
description: Recipe Book for the Rolstad Family
paginate: 5
