excerpt_separator: ""
pygments: true
markdown: kramdown
url: https://jrolstad.github.io/rolstad-recipes
repository_url: https://github.com/jrolstad/rolstad-recipes/blob/gh-pages
title: Rolstad Recipes
tagline: Rolstad Family Recipes
description: Recipe Book for the Rolstad Family
paginate: 5
