excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://jrolstad.github.io/rolstad-recipes
title: Rolstad Recipes
tagline: Rolstad Family Recipes
description: Recipe Book for the Rolstad Family
paginate: 5
